-- Table OUTILS_USAGER
SELECT COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'OUTILS_USAGER';

-- Table OUTILS_OUTILS
SELECT COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'OUTILS_OUTIL';

-- Table OUTILS_EMPRUNT
SELECT COLUMN_NAME, DATA_TYPE
FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'OUTILS_EMPRUNT';
--QUESTION 2
SELECT CONCAT(prenom, ' ', nom_famille) AS Nom_Complet
FROM OUTILS_USAGER;
--QUESTION 3
SELECT DISTINCT ville
FROM OUTILS_USAGER
ORDER BY ville;
--QUESTION 4
SELECT *
FROM OUTILS_OUTIL
ORDER BY nom, code_outil;
--QUESTION 5
SELECT num_emprunt
FROM OUTILS_EMPRUNT
WHERE date_retour IS NULL;
--QUESTION 6
SELECT *
FROM OUTILS_EMPRUNT
WHERE date_emprunt < TO_DATE('2014-01-01', 'YYYY-MM-DD');
--QUESTION 7
--la colonne 'couleur' n'existe pas, ,mais si elle existait voici la requette
--SELECT couleur, code_outil
--FROM OUTILS_OUTIL
--WHERE UPPER(NOM) LIKE 'J%';

--QUESTION 8
SELECT nom, code_outil
FROM OUTILS_OUTIL
WHERE fabricant = 'Stanley';

--QUESTION 9
SELECT nom, fabricant
FROM OUTILS_OUTIL
WHERE annee BETWEEN 2006 AND 2008;

--QUESTION 10
SELECT code_outil, nom
FROM OUTILS_OUTIL
WHERE caracteristiques != '20 volt';

--QUESTION 11
SELECT COUNT(*)
FROM OUTILS_OUTIL
WHERE fabricant != 'Makita';

--QUESTION 12
SELECT CONCAT(U.prenom, ' ', U.nom_famille) AS Nom_Complet,
       E.NUM_EMPRUNT,
       E.CODE_OUTIL,
       E.DATE_EMPRUNT,
       E.DATE_RETOUR
FROM OUTILS_USAGER U
JOIN OUTILS_EMPRUNT E ON U.NUM_USAGER = E.NUM_USAGER
WHERE U.VILLE IN ('Vancouver', 'Regina');

--QUESTION 13
SELECT O.nom, O.code_outil
FROM OUTILS_OUTIL O
JOIN OUTILS_EMPRUNT E ON O.code_outil = E.code_outil
WHERE E.date_retour IS NULL;

--QUESTION 14
SELECT NOM_FAMILLE, COURRIEL
FROM OUTILS_USAGER
WHERE NUM_USAGER NOT IN (SELECT NUM_USAGER FROM OUTILS_EMPRUNT);

--QUESTION 15
SELECT O.CODE_OUTIL, O.NOM, O.PRIX
FROM OUTILS_OUTIL O
LEFT OUTER JOIN OUTILS_EMPRUNT E ON O.CODE_OUTIL = E.CODE_OUTIL
WHERE E.NUM_EMPRUNT IS NULL

--QUESTION 16
SELECT NOM, PRIX
FROM OUTILS_OUTIL
WHERE FABRICANT = 'Makita' AND PRIX > (SELECT AVG(PRIX) FROM OUTILS_OUTIL);

--QUESTION 17
SELECT 
    U.NOM_FAMILLE,
    U.PRENOM,
    U.ADRESSE,
    E.CODE_OUTIL,
    O.NOM
FROM 
    OUTILS_USAGER U
INNER JOIN 
    OUTILS_EMPRUNT E ON U.NUM_USAGER = E.NUM_USAGER
INNER JOIN 
    OUTILS_OUTIL O ON E.CODE_OUTIL = O.CODE_OUTIL
WHERE 
    E.DATE_EMPRUNT > '2014-01-01'
ORDER BY 
    U.NOM_FAMILLE;
    
--QUESTION 18
SELECT 
    O.NOM, 
    O.PRIX
FROM 
    OUTILS_OUTIL O
JOIN 
    OUTILS_EMPRUNT E ON O.CODE_OUTIL = E.CODE_OUTIL
GROUP BY 
    O.CODE_OUTIL, O.NOM, O.PRIX
HAVING 
    COUNT(*) > 1;
    
--QUESTION 19
--avec jointure
SELECT U.NOM_FAMILLE, U.ADRESSE, U.VILLE
FROM OUTILS_USAGER U
INNER JOIN OUTILS_EMPRUNT E ON U.NUM_USAGER = E.NUM_USAGER;

--IN
SELECT NOM_FAMILLE, ADRESSE, VILLE
FROM OUTILS_USAGER
WHERE NUM_USAGER IN (SELECT NUM_USAGER FROM OUTILS_EMPRUNT);

--EXISTS
SELECT NOM_FAMILLE, ADRESSE, VILLE
FROM OUTILS_USAGER U
WHERE EXISTS (SELECT 1 FROM OUTILS_EMPRUNT E WHERE E.NUM_USAGER = U.NUM_USAGER);

--QUESTION 20
SELECT FABRICANT AS MARQUE, AVG(PRIX) AS MOYENNE_PRIX
FROM OUTILS_OUTIL
GROUP BY FABRICANT;

--QUESTION 21
SELECT U.VILLE, SUM(O.PRIX) AS SOMME_PRIX
FROM OUTILS_USAGER U
JOIN OUTILS_EMPRUNT E ON U.NUM_USAGER = E.NUM_USAGER
JOIN OUTILS_OUTIL O ON E.CODE_OUTIL = O.CODE_OUTIL
GROUP BY U.VILLE
ORDER BY SOMME_PRIX DESC;

--QUESTION 22
INSERT INTO OUTILS_OUTIL (CODE_OUTIL, NOM, FABRICANT, CARACTERISTIQUES, ANNEE, PRIX)
VALUES ('0101', 'NouveauOutil', 'NouveauFabricant', 'CaracteristiquesNouvelles', 2024, 99.99);


--QUESTION 23
INSERT INTO OUTILS_OUTIL (CODE_OUTIL, NOM, FABRICANT, CARACTERISTIQUES, ANNEE, PRIX)
VALUES ('0102', 'NouveauOutil', 'NouveauFabricant', 'CaracteristiquesNouvelles', 2024, 99.99);


--QUESTION 24
DELETE FROM OUTILS_OUTIL
WHERE CODE_OUTIL IN ('0101', '0102');

--QUESTION 25
UPDATE OUTILS_USAGER
SET NOM_FAMILLE = UPPER(NOM_FAMILLE);
